DATABASE_URL=postgresql://postgres.chnybctlzagtdrggjjhg:Z1cjMMi1CSGfiSlX@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
NEXT_PUBLIC_SUPABASE_URL=https://chnybctlzagtdrggjjhg.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNobnliY3RsemFndGRyZ2dqamhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU2OTI1NzksImV4cCI6MjEwMTI2ODU3OX0.xj2C7Vi3zK4hxLjzkzFY55Lfi-Oy9xN2StHxeBxKi7o
NEXT_PUBLIC_SITE_URL=http://localhost:3000
